development:
  sessions:
    default:
      database: marysia_dev
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: marysia_production
      hosts:
        - localhost:27017